# constraints
# ad9361 (SWAP == 0x1)

set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports CLK_40M_DAC_nSYNC]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports CLK_40M_DAC_SCLK]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports CLK_40M_DAC_DIN]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports PPS_IN]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports CLK_40MHz_FPGA]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports CLKIN_10MHz]
#DONT KNOW WHAT IS REQ
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports CLKIN_10MHz_REQ]
set_property PACKAGE_PIN J20 [get_ports LED0]
set_property PACKAGE_PIN H20 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]

set_property IOSTANDARD LVCMOS33 [get_ports fixed_io_mio[12]]
set_property  -dict {PACKAGE_PIN D9   PULLTYPE PULLUP} [get_ports fixed_io_mio[12]]

set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_n]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_p]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_n]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_p]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[0]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[0]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[1]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[1]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[2]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[2]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[3]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[3]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[4]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[4]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[5]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[5]}]

set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVDS_25} [get_ports tx_clk_out_n]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVDS_25} [get_ports tx_clk_out_p]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVDS_25} [get_ports tx_frame_out_n]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVDS_25} [get_ports tx_frame_out_p]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[0]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[0]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[1]}]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[1]}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[2]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[2]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[3]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[3]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[4]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[4]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[5]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[5]}]

set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS25} [get_ports {gpio_status[0]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS25} [get_ports {gpio_status[1]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS25} [get_ports {gpio_status[2]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS25} [get_ports {gpio_status[3]}]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS25} [get_ports {gpio_status[4]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS25} [get_ports {gpio_status[5]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS25} [get_ports {gpio_status[6]}]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS25} [get_ports {gpio_status[7]}]

set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[0]}]
# CHECK AS schematic says EXT_GPIO G15 K14 J14 N15 
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports {gpio_ctl[1]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {gpio_ctl[2]}]
set_property -dict {PACKAGE_PIN U9 IOSTANDARD LVCMOS33} [get_ports {gpio_ctl[3]}]

set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS25} [get_ports gpio_en_agc]
#set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS25} [get_ports gpio_sync]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS25} [get_ports gpio_resetb]
#set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports gpio_clksel]

set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS25} [get_ports txnrx]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS25} [get_ports enable]

set_property  -dict {PACKAGE_PIN  M15  IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports iic_scl]
set_property  -dict {PACKAGE_PIN  K16  IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports iic_sda]

set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS25 PULLTYPE PULLUP} [get_ports spi_csn]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS25} [get_ports spi_mosi]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS25} [get_ports spi_miso]

set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS25} [get_ports clkout_in]

set_property  -dict {PACKAGE_PIN  K14  IOSTANDARD LVCMOS33} [get_ports pl_spi_clk_o]
set_property  -dict {PACKAGE_PIN  J14  IOSTANDARD LVCMOS33} [get_ports pl_spi_miso]
set_property  -dict {PACKAGE_PIN  N15  IOSTANDARD LVCMOS33} [get_ports pl_spi_mosi]

#create_clock -period 8.000 -name rx_clk [get_ports rx_clk_in_p]
create_clock -name rx_clk       -period  4 [get_ports rx_clk_in_p]

# probably gone in 2016.4

create_clock -name clk_fpga_0 -period 10 [get_pins "i_system_wrapper/system_i/sys_ps7/inst/PS7_i/FCLKCLK[0]"]
create_clock -name clk_fpga_1 -period  5 [get_pins "i_system_wrapper/system_i/sys_ps7/inst/PS7_i/FCLKCLK[1]"]

create_clock -name spi0_clk      -period 40   [get_pins -hier */EMIOSPI0SCLKO]

set_input_jitter clk_fpga_0 0.300
set_input_jitter clk_fpga_1 0.150

set_property IOSTANDARD LVCMOS33 [get_ports *fixed_io_mio*]
set_property SLEW SLOW [get_ports *fixed_io_mio*]
set_property DRIVE 8 [get_ports *fixed_io_mio*]


set_property IOSTANDARD LVCMOS25 [get_ports fixed_io_ps_srstb]



set_property IOSTANDARD SSTL15_T_DCI [get_ports *fixed_io_ddr_vr*]
set_property SLEW FAST [get_ports *fixed_io_ddr_vr*]
set_property PACKAGE_PIN G5 [get_ports fixed_io_ddr_vrn]
set_property PACKAGE_PIN H5 [get_ports fixed_io_ddr_vrp]

set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr_ck_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr_ck_p]
set_property SLEW FAST [get_ports ddr_ck_n]
set_property SLEW FAST [get_ports ddr_ck_p]
set_property PACKAGE_PIN M2 [get_ports ddr_ck_n]
set_property PACKAGE_PIN L2 [get_ports ddr_ck_p]

set_property IOSTANDARD SSTL15 [get_ports *ddr_addr*]
set_property SLEW SLOW [get_ports *ddr_addr*]
set_property PACKAGE_PIN N2 [get_ports {ddr_addr[0]}]
set_property PACKAGE_PIN K2 [get_ports {ddr_addr[1]}]
set_property PACKAGE_PIN M3 [get_ports {ddr_addr[2]}]
set_property PACKAGE_PIN K3 [get_ports {ddr_addr[3]}]
set_property PACKAGE_PIN M4 [get_ports {ddr_addr[4]}]
set_property PACKAGE_PIN L1 [get_ports {ddr_addr[5]}]
set_property PACKAGE_PIN L4 [get_ports {ddr_addr[6]}]
set_property PACKAGE_PIN K4 [get_ports {ddr_addr[7]}]
set_property PACKAGE_PIN K1 [get_ports {ddr_addr[8]}]
set_property PACKAGE_PIN J4 [get_ports {ddr_addr[9]}]
set_property PACKAGE_PIN F5 [get_ports {ddr_addr[10]}]
set_property PACKAGE_PIN G4 [get_ports {ddr_addr[11]}]
set_property PACKAGE_PIN E4 [get_ports {ddr_addr[12]}]
set_property PACKAGE_PIN D4 [get_ports {ddr_addr[13]}]
set_property PACKAGE_PIN F4 [get_ports {ddr_addr[14]}]

set_property IOSTANDARD SSTL15 [get_ports *ddr_ba*]
set_property SLEW SLOW [get_ports *ddr_ba*]
set_property PACKAGE_PIN L5 [get_ports {ddr_ba[0]}]
set_property PACKAGE_PIN R4 [get_ports {ddr_ba[1]}]
set_property PACKAGE_PIN J5 [get_ports {ddr_ba[2]}]

set_property IOSTANDARD SSTL15 [get_ports ddr_reset_n]
set_property SLEW FAST [get_ports ddr_reset_n]
set_property PACKAGE_PIN B4 [get_ports ddr_reset_n]
set_property IOSTANDARD SSTL15 [get_ports ddr_cs_n]
set_property SLEW SLOW [get_ports ddr_cs_n]
set_property PACKAGE_PIN N1 [get_ports ddr_cs_n]
set_property IOSTANDARD SSTL15 [get_ports ddr_ras_n]
set_property SLEW SLOW [get_ports ddr_ras_n]
set_property PACKAGE_PIN P4 [get_ports ddr_ras_n]
set_property IOSTANDARD SSTL15 [get_ports ddr_cas_n]
set_property SLEW SLOW [get_ports ddr_cas_n]
set_property PACKAGE_PIN P5 [get_ports ddr_cas_n]
set_property IOSTANDARD SSTL15 [get_ports ddr_we_n]
set_property SLEW SLOW [get_ports ddr_we_n]
set_property PACKAGE_PIN M5 [get_ports ddr_we_n]
set_property IOSTANDARD SSTL15 [get_ports ddr_cke]
set_property SLEW SLOW [get_ports ddr_cke]
set_property PACKAGE_PIN N3 [get_ports ddr_cke]
set_property IOSTANDARD SSTL15 [get_ports ddr_odt]
set_property SLEW SLOW [get_ports ddr_odt]
set_property PACKAGE_PIN N5 [get_ports ddr_odt]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {*ddr_dq[*]}]
set_property SLEW FAST [get_ports {*ddr_dq[*]}]
set_property PACKAGE_PIN C3 [get_ports ddr_dq[0]]
set_property PACKAGE_PIN B3 [get_ports ddr_dq[1]]
set_property PACKAGE_PIN A2 [get_ports ddr_dq[2]]
set_property PACKAGE_PIN A4 [get_ports ddr_dq[3]]
set_property PACKAGE_PIN D3 [get_ports ddr_dq[4]]
set_property PACKAGE_PIN D1 [get_ports ddr_dq[5]]
set_property PACKAGE_PIN C1 [get_ports ddr_dq[6]]
set_property PACKAGE_PIN E1 [get_ports ddr_dq[7]]
set_property PACKAGE_PIN E2 [get_ports ddr_dq[8]]
set_property PACKAGE_PIN E3 [get_ports ddr_dq[9]]
set_property PACKAGE_PIN G3 [get_ports ddr_dq[10]]
set_property PACKAGE_PIN H3 [get_ports ddr_dq[11]]
set_property PACKAGE_PIN J3 [get_ports ddr_dq[12]]
set_property PACKAGE_PIN H2 [get_ports ddr_dq[13]]
set_property PACKAGE_PIN H1 [get_ports ddr_dq[14]]
set_property PACKAGE_PIN J1 [get_ports ddr_dq[15]]
set_property PACKAGE_PIN P1 [get_ports ddr_dq[16]]
set_property PACKAGE_PIN P3 [get_ports ddr_dq[17]]
set_property PACKAGE_PIN R3 [get_ports ddr_dq[18]]
set_property PACKAGE_PIN R1 [get_ports ddr_dq[19]]
set_property PACKAGE_PIN T4 [get_ports ddr_dq[20]]
set_property PACKAGE_PIN U4 [get_ports ddr_dq[21]]
set_property PACKAGE_PIN U2 [get_ports ddr_dq[22]]
set_property PACKAGE_PIN U3 [get_ports ddr_dq[23]]
set_property PACKAGE_PIN V1 [get_ports ddr_dq[24]]
set_property PACKAGE_PIN Y3 [get_ports ddr_dq[25]]
set_property PACKAGE_PIN W1 [get_ports ddr_dq[26]]
set_property PACKAGE_PIN Y4 [get_ports ddr_dq[27]]
set_property PACKAGE_PIN Y2 [get_ports ddr_dq[28]]
set_property PACKAGE_PIN W3 [get_ports ddr_dq[29]]
set_property PACKAGE_PIN V2 [get_ports ddr_dq[30]]
set_property PACKAGE_PIN V3 [get_ports ddr_dq[31]]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {*ddr_dm[*]}]
set_property SLEW FAST [get_ports {*ddr_dm[*]}]
set_property PACKAGE_PIN A1 [get_ports ddr_dm[0]]
set_property PACKAGE_PIN F1 [get_ports ddr_dm[1]]
set_property PACKAGE_PIN T1 [get_ports ddr_dm[2]]
set_property PACKAGE_PIN Y1 [get_ports ddr_dm[3]]

set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports *ddr_dqs*]
set_property SLEW FAST [get_ports *ddr_dqs*]
set_property PACKAGE_PIN B2 [get_ports {ddr_dqs_n[0]}]
set_property PACKAGE_PIN C2 [get_ports {ddr_dqs_p[0]}]
set_property PACKAGE_PIN F2 [get_ports {ddr_dqs_n[1]}]
set_property PACKAGE_PIN G2 [get_ports {ddr_dqs_p[1]}]
set_property PACKAGE_PIN T2 [get_ports {ddr_dqs_n[2]}]
set_property PACKAGE_PIN R2 [get_ports {ddr_dqs_p[2]}]
set_property PACKAGE_PIN W4 [get_ports {ddr_dqs_n[3]}]
set_property PACKAGE_PIN W5 [get_ports {ddr_dqs_p[3]}]

set_false_path -from [get_pins {i_system_wrapper/system_i/axi_ad9361/inst/i_rx/i_up_adc_common/up_adc_gpio_out_int_reg[0]/C}]
set_false_path -from [get_pins {i_system_wrapper/system_i/axi_ad9361/inst/i_tx/i_up_dac_common/up_dac_gpio_out_int_reg[0]/C}]
set_false_path -from [get_pins {i_system_wrapper/system_i/manual_decim/U0/gpio_core_1/Not_Dual.gpio_Data_Out_reg[0]/C}]



