-- Generated by PeakRDL-regblock-vhdl - A free and open-source VHDL generator
--  https://github.com/SystemRDL/PeakRDL-regblock-vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

package msk_top_regs_pkg is

    constant MSK_TOP_REGS_DATA_WIDTH : positive := 32;
    constant MSK_TOP_REGS_MIN_ADDR_WIDTH : positive := 8;
    constant MSK_TOP_REGS_SIZE : positive := 144;

    type \msk_top_regs.msk_stat_0.demod_sync_lock_in_t\ is record
        next_q : std_logic;
    end record;

    type \msk_top_regs.msk_stat_0.tx_enable_in_t\ is record
        next_q : std_logic;
    end record;

    type \msk_top_regs.msk_stat_0.rx_enable_in_t\ is record
        next_q : std_logic;
    end record;

    type \msk_top_regs.msk_stat_0.tx_axis_valid_in_t\ is record
        next_q : std_logic;
    end record;

    type \msk_top_regs.msk_stat_0_in_t\ is record
        demod_sync_lock : \msk_top_regs.msk_stat_0.demod_sync_lock_in_t\;
        tx_enable : \msk_top_regs.msk_stat_0.tx_enable_in_t\;
        rx_enable : \msk_top_regs.msk_stat_0.rx_enable_in_t\;
        tx_axis_valid : \msk_top_regs.msk_stat_0.tx_axis_valid_in_t\;
    end record;

    type \msk_top_regs.msk_stat_1__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.msk_stat_2__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.stat_32_bits__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.stat_32_errs__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.stat_32_lpf_acc_desc_8cebc7dc_name_f20c6670__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.stat_32_lpf_acc_desc_dea6bd99_name_758fd0ce__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.msk_stat_3__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.observation_data_data_0c017ef4_desc_64ff3689_name_d8ad3b25__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.observation_data_data_0515efaa_desc_ebde6d39_name_2c154788__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.observation_data_data_25a21249_desc_417e1c96_name_3b640507__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.observation_data_data_272a00b6_desc_70869502_name_3de9a0d3__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.rx_power__external_in_t\ is record
        rd_ack : std_logic;
        rd_data : std_logic_vector(31 downto 0);
    end record;

    type msk_top_regs_in_t is record
        MSK_Status : \msk_top_regs.msk_stat_0_in_t\;
        Tx_Bit_Count : \msk_top_regs.msk_stat_1__external_in_t\;
        Tx_Enable_Count : \msk_top_regs.msk_stat_2__external_in_t\;
        PRBS_Bit_Count : \msk_top_regs.stat_32_bits__external_in_t\;
        PRBS_Error_Count : \msk_top_regs.stat_32_errs__external_in_t\;
        LPF_Accum_F1 : \msk_top_regs.stat_32_lpf_acc_desc_8cebc7dc_name_f20c6670__external_in_t\;
        LPF_Accum_F2 : \msk_top_regs.stat_32_lpf_acc_desc_dea6bd99_name_758fd0ce__external_in_t\;
        axis_xfer_count : \msk_top_regs.msk_stat_3__external_in_t\;
        f1_nco_adjust : \msk_top_regs.observation_data_data_0c017ef4_desc_64ff3689_name_d8ad3b25__external_in_t\;
        f2_nco_adjust : \msk_top_regs.observation_data_data_0515efaa_desc_ebde6d39_name_2c154788__external_in_t\;
        f1_error : \msk_top_regs.observation_data_data_25a21249_desc_417e1c96_name_3b640507__external_in_t\;
        f2_error : \msk_top_regs.observation_data_data_272a00b6_desc_70869502_name_3de9a0d3__external_in_t\;
        rx_power : \msk_top_regs.rx_power__external_in_t\;
    end record;

    type \msk_top_regs.msk_init.txrxinit_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_init.txinit_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_init.rxinit_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_init_out_t\ is record
        txrxinit : \msk_top_regs.msk_init.txrxinit_out_t\;
        txinit : \msk_top_regs.msk_init.txinit_out_t\;
        rxinit : \msk_top_regs.msk_init.rxinit_out_t\;
    end record;

    type \msk_top_regs.msk_ctrl.ptt_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_ctrl.loopback_ena_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_ctrl.rx_invert_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_ctrl.clear_counts_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_ctrl.diff_encoder_loopback_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.msk_ctrl_out_t\ is record
        ptt : \msk_top_regs.msk_ctrl.ptt_out_t\;
        loopback_ena : \msk_top_regs.msk_ctrl.loopback_ena_out_t\;
        rx_invert : \msk_top_regs.msk_ctrl.rx_invert_out_t\;
        clear_counts : \msk_top_regs.msk_ctrl.clear_counts_out_t\;
        diff_encoder_loopback : \msk_top_regs.msk_ctrl.diff_encoder_loopback_out_t\;
    end record;

    type \msk_top_regs.msk_stat_1__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.msk_stat_2__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.config_nco_fw_desc_c4924cc6_name_0c494469.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_nco_fw_desc_c4924cc6_name_0c494469_out_t\ is record
        config_data : \msk_top_regs.config_nco_fw_desc_c4924cc6_name_0c494469.config_data_out_t\;
    end record;

    type \msk_top_regs.config_nco_fw_desc_94d7aaf5_name_84dd0c1c.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_nco_fw_desc_94d7aaf5_name_84dd0c1c_out_t\ is record
        config_data : \msk_top_regs.config_nco_fw_desc_94d7aaf5_name_84dd0c1c.config_data_out_t\;
    end record;

    type \msk_top_regs.config_nco_fw_desc_42134a4f_name_d97dbd51.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_nco_fw_desc_42134a4f_name_d97dbd51_out_t\ is record
        config_data : \msk_top_regs.config_nco_fw_desc_42134a4f_name_d97dbd51.config_data_out_t\;
    end record;

    type \msk_top_regs.config_nco_fw_desc_16fb48c8_name_8d01a20d.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_nco_fw_desc_16fb48c8_name_8d01a20d_out_t\ is record
        config_data : \msk_top_regs.config_nco_fw_desc_16fb48c8_name_8d01a20d.config_data_out_t\;
    end record;

    type \msk_top_regs.config_nco_fw_desc_43c0828f_name_bdc60ecf.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_nco_fw_desc_43c0828f_name_bdc60ecf_out_t\ is record
        config_data : \msk_top_regs.config_nco_fw_desc_43c0828f_name_bdc60ecf.config_data_out_t\;
    end record;

    type \msk_top_regs.lpf_config_0.lpf_freeze_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.lpf_config_0.lpf_zero_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.lpf_config_0.prbs_reserved_out_t\ is record
        value : std_logic_vector(5 downto 0);
    end record;

    type \msk_top_regs.lpf_config_0.lpf_alpha_out_t\ is record
        value : std_logic_vector(23 downto 0);
    end record;

    type \msk_top_regs.lpf_config_0_out_t\ is record
        lpf_freeze : \msk_top_regs.lpf_config_0.lpf_freeze_out_t\;
        lpf_zero : \msk_top_regs.lpf_config_0.lpf_zero_out_t\;
        prbs_reserved : \msk_top_regs.lpf_config_0.prbs_reserved_out_t\;
        lpf_alpha : \msk_top_regs.lpf_config_0.lpf_alpha_out_t\;
    end record;

    type \msk_top_regs.lpf_config_1.i_gain_out_t\ is record
        value : std_logic_vector(23 downto 0);
    end record;

    type \msk_top_regs.lpf_config_1.i_shift_out_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \msk_top_regs.lpf_config_1_out_t\ is record
        i_gain : \msk_top_regs.lpf_config_1.i_gain_out_t\;
        i_shift : \msk_top_regs.lpf_config_1.i_shift_out_t\;
    end record;

    type \msk_top_regs.data_width_desc_58c848dd_name_2fbd8eba.data_width_out_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \msk_top_regs.data_width_desc_58c848dd_name_2fbd8eba_out_t\ is record
        data_width : \msk_top_regs.data_width_desc_58c848dd_name_2fbd8eba.data_width_out_t\;
    end record;

    type \msk_top_regs.data_width_desc_6097df38_name_4609588b.data_width_out_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \msk_top_regs.data_width_desc_6097df38_name_4609588b_out_t\ is record
        data_width : \msk_top_regs.data_width_desc_6097df38_name_4609588b.data_width_out_t\;
    end record;

    type \msk_top_regs.prbs_ctrl.prbs_sel_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.prbs_ctrl.prbs_error_insert_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.prbs_ctrl.prbs_clear_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.prbs_ctrl.prbs_manual_sync_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.prbs_ctrl.prbs_reserved_out_t\ is record
        value : std_logic_vector(11 downto 0);
    end record;

    type \msk_top_regs.prbs_ctrl.prbs_sync_threshold_out_t\ is record
        value : std_logic_vector(15 downto 0);
    end record;

    type \msk_top_regs.prbs_ctrl_out_t\ is record
        prbs_sel : \msk_top_regs.prbs_ctrl.prbs_sel_out_t\;
        prbs_error_insert : \msk_top_regs.prbs_ctrl.prbs_error_insert_out_t\;
        prbs_clear : \msk_top_regs.prbs_ctrl.prbs_clear_out_t\;
        prbs_manual_sync : \msk_top_regs.prbs_ctrl.prbs_manual_sync_out_t\;
        prbs_reserved : \msk_top_regs.prbs_ctrl.prbs_reserved_out_t\;
        prbs_sync_threshold : \msk_top_regs.prbs_ctrl.prbs_sync_threshold_out_t\;
    end record;

    type \msk_top_regs.config_prbs_seed.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_prbs_seed_out_t\ is record
        config_data : \msk_top_regs.config_prbs_seed.config_data_out_t\;
    end record;

    type \msk_top_regs.config_prbs_poly.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_prbs_poly_out_t\ is record
        config_data : \msk_top_regs.config_prbs_poly.config_data_out_t\;
    end record;

    type \msk_top_regs.config_prbs_errmask.config_data_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \msk_top_regs.config_prbs_errmask_out_t\ is record
        config_data : \msk_top_regs.config_prbs_errmask.config_data_out_t\;
    end record;

    type \msk_top_regs.stat_32_bits__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.stat_32_errs__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.stat_32_lpf_acc_desc_8cebc7dc_name_f20c6670__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.stat_32_lpf_acc_desc_dea6bd99_name_758fd0ce__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.msk_stat_3__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.rx_sample_discard.rx_sample_discard_out_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \msk_top_regs.rx_sample_discard.rx_nco_discard_out_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \msk_top_regs.rx_sample_discard_out_t\ is record
        rx_sample_discard : \msk_top_regs.rx_sample_discard.rx_sample_discard_out_t\;
        rx_nco_discard : \msk_top_regs.rx_sample_discard.rx_nco_discard_out_t\;
    end record;

    type \msk_top_regs.lpf_config_2.p_gain_out_t\ is record
        value : std_logic_vector(23 downto 0);
    end record;

    type \msk_top_regs.lpf_config_2.p_shift_out_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \msk_top_regs.lpf_config_2_out_t\ is record
        p_gain : \msk_top_regs.lpf_config_2.p_gain_out_t\;
        p_shift : \msk_top_regs.lpf_config_2.p_shift_out_t\;
    end record;

    type \msk_top_regs.observation_data_data_0c017ef4_desc_64ff3689_name_d8ad3b25__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.observation_data_data_0515efaa_desc_ebde6d39_name_2c154788__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.observation_data_data_25a21249_desc_417e1c96_name_3b640507__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.observation_data_data_272a00b6_desc_70869502_name_3de9a0d3__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type \msk_top_regs.tx_sync_ctrl.tx_sync_ena_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.tx_sync_ctrl.tx_sync_force_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.tx_sync_ctrl.tx_sync_f1_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.tx_sync_ctrl.tx_sync_f2_out_t\ is record
        value : std_logic;
    end record;

    type \msk_top_regs.tx_sync_ctrl_out_t\ is record
        tx_sync_ena : \msk_top_regs.tx_sync_ctrl.tx_sync_ena_out_t\;
        tx_sync_force : \msk_top_regs.tx_sync_ctrl.tx_sync_force_out_t\;
        tx_sync_f1 : \msk_top_regs.tx_sync_ctrl.tx_sync_f1_out_t\;
        tx_sync_f2 : \msk_top_regs.tx_sync_ctrl.tx_sync_f2_out_t\;
    end record;

    type \msk_top_regs.tx_sync_cnt.tx_sync_cnt_out_t\ is record
        value : std_logic_vector(23 downto 0);
    end record;

    type \msk_top_regs.tx_sync_cnt_out_t\ is record
        tx_sync_cnt : \msk_top_regs.tx_sync_cnt.tx_sync_cnt_out_t\;
    end record;

    type \msk_top_regs.lowpass_ema_alpha.alpha_out_t\ is record
        value : std_logic_vector(17 downto 0);
    end record;

    type \msk_top_regs.lowpass_ema_alpha_out_t\ is record
        alpha : \msk_top_regs.lowpass_ema_alpha.alpha_out_t\;
    end record;

    type \msk_top_regs.rx_power__external_out_t\ is record
        req : std_logic;
        req_is_wr : std_logic;
    end record;

    type msk_top_regs_out_t is record
        MSK_Init : \msk_top_regs.msk_init_out_t\;
        MSK_Control : \msk_top_regs.msk_ctrl_out_t\;
        Tx_Bit_Count : \msk_top_regs.msk_stat_1__external_out_t\;
        Tx_Enable_Count : \msk_top_regs.msk_stat_2__external_out_t\;
        Fb_FreqWord : \msk_top_regs.config_nco_fw_desc_c4924cc6_name_0c494469_out_t\;
        TX_F1_FreqWord : \msk_top_regs.config_nco_fw_desc_94d7aaf5_name_84dd0c1c_out_t\;
        TX_F2_FreqWord : \msk_top_regs.config_nco_fw_desc_42134a4f_name_d97dbd51_out_t\;
        RX_F1_FreqWord : \msk_top_regs.config_nco_fw_desc_16fb48c8_name_8d01a20d_out_t\;
        RX_F2_FreqWord : \msk_top_regs.config_nco_fw_desc_43c0828f_name_bdc60ecf_out_t\;
        LPF_Config_0 : \msk_top_regs.lpf_config_0_out_t\;
        LPF_Config_1 : \msk_top_regs.lpf_config_1_out_t\;
        Tx_Data_Width : \msk_top_regs.data_width_desc_58c848dd_name_2fbd8eba_out_t\;
        Rx_Data_Width : \msk_top_regs.data_width_desc_6097df38_name_4609588b_out_t\;
        PRBS_Control : \msk_top_regs.prbs_ctrl_out_t\;
        PRBS_Initial_State : \msk_top_regs.config_prbs_seed_out_t\;
        PRBS_Polynomial : \msk_top_regs.config_prbs_poly_out_t\;
        PRBS_Error_Mask : \msk_top_regs.config_prbs_errmask_out_t\;
        PRBS_Bit_Count : \msk_top_regs.stat_32_bits__external_out_t\;
        PRBS_Error_Count : \msk_top_regs.stat_32_errs__external_out_t\;
        LPF_Accum_F1 : \msk_top_regs.stat_32_lpf_acc_desc_8cebc7dc_name_f20c6670__external_out_t\;
        LPF_Accum_F2 : \msk_top_regs.stat_32_lpf_acc_desc_dea6bd99_name_758fd0ce__external_out_t\;
        axis_xfer_count : \msk_top_regs.msk_stat_3__external_out_t\;
        Rx_Sample_Discard : \msk_top_regs.rx_sample_discard_out_t\;
        LPF_Config_2 : \msk_top_regs.lpf_config_2_out_t\;
        f1_nco_adjust : \msk_top_regs.observation_data_data_0c017ef4_desc_64ff3689_name_d8ad3b25__external_out_t\;
        f2_nco_adjust : \msk_top_regs.observation_data_data_0515efaa_desc_ebde6d39_name_2c154788__external_out_t\;
        f1_error : \msk_top_regs.observation_data_data_25a21249_desc_417e1c96_name_3b640507__external_out_t\;
        f2_error : \msk_top_regs.observation_data_data_272a00b6_desc_70869502_name_3de9a0d3__external_out_t\;
        Tx_Sync_Ctrl : \msk_top_regs.tx_sync_ctrl_out_t\;
        Tx_Sync_Cnt : \msk_top_regs.tx_sync_cnt_out_t\;
        lowpass_ema_alpha1 : \msk_top_regs.lowpass_ema_alpha_out_t\;
        lowpass_ema_alpha2 : \msk_top_regs.lowpass_ema_alpha_out_t\;
        rx_power : \msk_top_regs.rx_power__external_out_t\;
    end record;
end package;
